### ISSUE TITLE
 collective.recipe.environment 1.0.0 broken under Python 3

### ISSUE THREAD

**Issue by cas--** [collective/collective.recipe.environment#3]
The latest release of `collective.recipe.environment 1.0.0` cannot be installed under Python 3 due to the use of `iteritems` in this recent commit [d95b0a4ce7](https://github.com/collective/collective.recipe.environment/commit/d95b0a4ce776521776ec0b9b0d027f344abf37d0#diff-35d550b6af6e449f4f6e9e8dbc361b84R16) 

```
File "collective.recipe.environment-1.0.0-py3.5.egg/collective/recipe/environment/__init__.py", line 16, in __init__
    env_vars = {k: self._escape_var_substitutions(v) for (k, v) in os.environ.iteritems()}
AttributeError: '_Environ' object has no attribute 'iteritems'
```

**Comment by rafaelbco** [comment]
Sorry about that. Python 3 is indeed not supported, as indicated in the classifiers in `setup.py`.

I'd like to support Python 3, but it is beyond my capacity at this moment. If a PR is written in order to accomplish that then I'm happy to accept and maintain compatibility with 2.7 and 3 in the next changes.

Such PR must include provisions to make Travis tests run in all supported Python versions.

**Comment by cas--** [comment]
The previous version `0.2` is fine under Python 3. All that is required is to use `items` instead of `iteritems` to keep compatibility.

**Comment by rafaelbco** [comment]
@cas-- You can submit a PR in order to change only `iteritems` to `items`, and I'll accept it. 

I cannot, however, officially announce it (in the docs and the `setup.py` classifiers) as Python 3 compatible if Travis CI is not setup to run the required tests. Somebody could break the compatibility again in the future.

**Comment by cas--** [comment]
>You can submit a PR 

Sure

However there is an issue with local and travis testing:

### Local testing
```
Expected:
    start ...
    some_value
    ...
Got:
    start Installing environment.
    Installing print.
    some_value
    <BLANKLINE>
```

### Travis test 
with `<BLANKLINE>` fix for local testing applied
```
Expected:
    start ...
    some_value
    <BLANKLINE>
Got:
    start Installing environment.
    Installing print.
    some_value
    Not found: /tmp/tmpFuQVzwbuildouttests/mr.scripty/
    Not found: /tmp/tmpFuQVzwbuildouttests/mr.scripty/
    Couldn't find index page for 'mr.scripty' (maybe misspelled?)
    <BLANKLINE>
```

**Comment by rafaelbco** [comment]
@cas-- thank you very much for the pull request. 

As for the testing inconsistencies I made an attempt to fix them and it seems to have worked, if I understood well. Check my last commit.

Regardless I'm closing the issue and cutting a new release.
